plugins {
    id 'idea'
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '6.0.+'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
}

def secretsFile = project.file(".secret.properties")
if (secretsFile.exists()) {
    ant.property(file: secretsFile, prefix: 'secret')
}

def getSecret = { key, fallback = null ->
    ant.properties["secret.${key}"] ?: providers.environmentVariable(key).orNull ?: fallback
}

repositories {
    maven { url = uri("https://maven.shedaniel.me/") }
    maven { url = uri("https://maven.terraformersmc.com/releases/") }
    maven { url = uri("https://maven.minecraftforge.net") }
    maven {
        url = uri('https://jitpack.io')
        content {
            includeGroupByRegex 'com\\.github\\..*'
        }
    }
    maven {
        url = uri("https://maven.pkg.github.com/Robak132/LibGui-Forge")
        credentials {
            username = getSecret("GITHUB_ACTOR")
            password = getSecret("GITHUB_TOKEN")
        }
    }
    mavenCentral()
}

ant.property(file: project.file('gradle.properties'), prefix: 'mod')
def getModProperty = { key ->
    ant.properties["mod.${key}"] ?: providers.gradleProperty(key).get()
}
def modId = getModProperty('mod_id')

version = getModProperty('mod_version')
group = getModProperty('maven_group')
base.archivesName = getModProperty('archives_base_name')

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

minecraft {
    mappings channel: 'parchment', version: '2023.09.03-1.20.1'
    copyIdeResources = true
    generateRunFolders = true
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${modId}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            property 'forge.enabledGameTestNamespaces', modId
        }

        server {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            property 'forge.enabledGameTestNamespaces', modId
        }

        gameTestServer {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            property 'forge.enabledGameTestNamespaces', modId
        }

        data {
            workingDirectory project.file('run-data')

            args '--mod', modId, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation 'org.projectlombok:lombok:1.18.42'
    minecraft("net.minecraftforge:forge:1.20.1-47.4.0")
    api project(':LibGui-Forge')
    api fg.deobf("me.shedaniel.cloth:cloth-config-forge:11.1.136")
    compileOnly fg.deobf("dev.emi:emi-forge:1.1.24+1.20.1")
    runtimeOnly fg.deobf("dev.emi:emi-forge:1.1.24+1.20.1")

    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

// Proper Mixin setup for Forge
mixin {
    add sourceSets.main, 'mixins.mcrgb_forge.refmap.json'
    config 'mixins.mcrgb_forge.json'

    debug.verbose = true
    debug.export = true
}
