pluginManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = "https://maven.shedaniel.me/" }
        maven { url = 'https://maven.parchmentmc.org' }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'MCRGB-Forge'

def libGuiProjectDir = file('../LibGui-Forge')
if (libGuiProjectDir.isDirectory()) {
    include 'LibGui-Forge'
    project(':LibGui-Forge').projectDir = libGuiProjectDir
}
